# Generated by Django 3.0.8 on 2020-10-21 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapto', '0002_auto_20201021_1712'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courses',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='courses',
            name='No_Of_Days',
            field=models.DateField(null=True),
        ),
    ]
