# Generated by Django 3.0.8 on 2020-10-21 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapto', '0003_auto_20201021_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='Udemy_Link',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='courses',
            name='No_Of_Days',
            field=models.DateField(blank=True, null=True),
        ),
    ]
