# Generated by Django 3.0.8 on 2020-10-21 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rapto', '0004_auto_20201022_0011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='No_Of_Days',
        ),
    ]
