# Generated by Django 3.0.8 on 2020-10-26 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapto', '0005_remove_courses_no_of_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50, null=True)),
                ('Message', models.TextField(null=True)),
                ('Email', models.EmailField(max_length=254, null=True)),
            ],
        ),
    ]
