# Generated by Django 3.0.8 on 2020-10-30 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapto', '0006_contactform'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='No_Of_Days',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
